In [43]:
import pandas as pd
requests_df = pd.read_csv("./data/Восток Синтетические данные.csv", sep=';', encoding="windows-1251")

In [44]:
requests_df

,Заявка,Тип заявки BK,Тип заявки HD,Начало,Окончание,Район,Адрес,Подключение,Гигабитное подключение
0,74198,Подключение,Конвергенция абонента,17.08.2026 20:00,17.08.2026 22:00,Кузьминки,"Город Москва, пр-кт.Волгоградский, д. 128 к 5",FMC,Нет
1,86160,Подключение,Конвергенция абонента,17.08.2026 18:00,17.08.2026 20:00,Таганский,"Город Москва, пер.Маяковского, д. 2",FMC,Нет
2,50104,Подключение,Заявка на подключение,17.08.2026 18:00,17.08.2026 20:00,Текстильщики,"Город Москва, ул.Грайвороновская, д. 10 к 2",NaN,Да
3,46393,Подключение,Конвергенция абонента,17.08.2026 20:00,17.08.2026 22:00,Рязанский,"Город Москва, ул.Михайлова, д. 14",FMC,Нет
4,10135,Подключение,Конвергенция абонента,17.08.2026 18:00,17.08.2026 20:00,Рязанский,"Город Москва, ул.3-я Институтская, д. 5 к 2",FMC,Нет
...,...,...,...,...,...,...,...,...,...
64,15648,Глобальная проблема,Информация,17.08.2026 16:00,17.08.2026 18:00,Басманный,"г.Город Москва, наб.Семеновская, д. 2/1",NaN,Нет
65,57299,Глобальная проблема,Авария,17.08.2026 20:00,17.08.2026 22:00,Кузьминки,"г.Город Москва, пр-кт.Волгоградский, д. 128к1",NaN,Нет
66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,Адрес Офиса,"г. Москва, ул Юных Ленинцев, д 83с 4",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
east_control_df = pd.read_csv("./data/Восток Контрольное распределение..csv", sep=';', encoding="windows-1251")

In [46]:
east_control_df

,Заявка,Тип заявки BK,Статус BK,Тип заявки HD,Начало,Окончание,Район,Адрес,Бригада,Подключение,Гигабитное подключение
0,305927238,Подключение,Не отправлена,Конвергенция абонента,17.08.2026 20:00,17.08.2026 22:00,Кузьминки,"Город Москва, пр-кт.Волгоградский, д. 128 к 5,...",NaN,FMC,Нет
1,305838184,Подключение,Отправлена,Конвергенция абонента,17.08.2026 18:00,17.08.2026 20:00,Таганский,"Город Москва, пер.Маяковского, д. 2, кв. 59",Бригада Соколов,FMC,Нет
2,305857695,Подключение,Отправлена,Заявка на подключение,17.08.2026 18:00,17.08.2026 20:00,Текстильщики,"Город Москва, ул.Грайвороновская, д. 10 к 2, к...",Бригада Мельников,NaN,Да
3,305849742,Подключение,Отправлена,Конвергенция абонента,17.08.2026 20:00,17.08.2026 22:00,Рязанский,"Город Москва, ул.Михайлова, д. 14, кв. 13",Бригада Матвеев,FMC,Нет
4,305886764,Подключение,Отправлена,Конвергенция абонента,17.08.2026 18:00,17.08.2026 20:00,Рязанский,"Город Москва, ул.3-я Институтская, д. 5 к 2, к...",Бригада Матвеев,FMC,Нет
...,...,...,...,...,...,...,...,...,...,...,...
61,305883073,Глобальная проблема,Выполнена,Информация,17.08.2026 10:00,17.08.2026 12:00,Выхино,"г.Город Москва, ул.Ташкентская, д. 16к2",Бригада Белузин,NaN,Нет
62,305896177,Глобальная проблема,Выполнена,Авария,17.08.2026 20:00,17.08.2026 22:00,Текстильщики,"г.Город Москва, ул.Саратовская, д. 16",Бригада Свеженцев,NaN,Нет
63,305896956,Глобальная проблема,Выполнена,Авария,17.08.2026 10:00,17.08.2026 12:00,Басманный,"г.Город Москва, наб.Семеновская, д. 3/1к2",Бригада Свеженцев,NaN,Нет
64,305898371,Глобальная проблема,Выполнена,Информация,17.08.2026 16:00,17.08.2026 18:00,Басманный,"г.Город Москва, наб.Семеновская, д. 2/1",Бригада Свеженцев,NaN,Нет
65,305914822,Глобальная проблема,Выполнена,Авария,17.08.2026 20:00,17.08.2026 22:00,Кузьминки,"г.Город Москва, пр-кт.Волгоградский, д. 128к1",Бригада Каушнян,NaN,Нет

In [47]:
east_control_df["Бригада"].dropna().unique().tolist()

['Бригада Соколов',
 'Бригада Мельников',
 'Бригада Матвеев',
 'Бригада Попов',
 'Бригада Арташкин',
 'Бригада Комарь',
 'Бригада Каушнян',
 'Бригада Зверев',
 'Бригада Перов',
 'Бригада Белузин',
 'Бригада Гусаковский',
 'Бригада Свеженцев']

In [48]:
east_control_df[["Бригада", "Начало", "Окончание"]]

              Бригада            Начало         Окончание
0                 NaN  17.08.2026 20:00  17.08.2026 22:00
1     Бригада Соколов  17.08.2026 18:00  17.08.2026 20:00
2   Бригада Мельников  17.08.2026 18:00  17.08.2026 20:00
3     Бригада Матвеев  17.08.2026 20:00  17.08.2026 22:00
4     Бригада Матвеев  17.08.2026 18:00  17.08.2026 20:00
..                ...               ...               ...
61    Бригада Белузин  17.08.2026 10:00  17.08.2026 12:00
62  Бригада Свеженцев  17.08.2026 20:00  17.08.2026 22:00
63  Бригада Свеженцев  17.08.2026 10:00  17.08.2026 12:00
64  Бригада Свеженцев  17.08.2026 16:00  17.08.2026 18:00
65    Бригада Каушнян  17.08.2026 20:00  17.08.2026 22:00

[66 rows x 3 columns]

In [49]:
def get_shifts(control_df: pd.DataFrame) -> pd.DataFrame:
    _start = pd.to_datetime(control_df["Начало"], format="%d.%m.%Y %H:%M")
    _end = pd.to_datetime(control_df["Окончание"], format="%d.%m.%Y %H:%M")

    shifts_df = (
        control_df.assign(_start=_start, _end=_end)
        .dropna(subset=["Бригада"])
        .groupby("Бригада")
        .agg(shift_start=("_start", "min"), shift_end=("_end", "max"))
        .reset_index()
        .sort_values("shift_start")
    )

    shifts_df["shift_start"] = shifts_df["shift_start"].dt.time
    shifts_df["shift_end"] = shifts_df["shift_end"].dt.time
    return shifts_df

In [50]:
east_shifts_df = get_shifts(east_control_df)

In [51]:
east_shifts_df.to_csv("./data/EastEngineersData.csv", index=False)

In [52]:
south_east_control_df = pd.read_csv("./data/Юго-восток Контрольное распределение.csv", sep=';', encoding="windows-1251")

In [53]:
south_east_shifts_df = get_shifts(south_east_control_df)
south_east_shifts_df.to_csv("./data/SouthEastEngineersData.csv", index=False)

In [54]:
south_east_control_df = pd.read_csv("./data/Югоцентр Контрольное распределение..csv", sep=';', encoding="windows-1251")

In [55]:
south_center_east_shifts_df = get_shifts(south_east_control_df)
south_center_east_shifts_df.to_csv("./data/SouthCenterEngineersData.csv", index=False)